parameters:
    webmozarts_messaging.asynchronous.command_bus.unhandled_messages_log_level: debug

services:

    webmozarts_messaging.asynchronous.gateway:
        class: Webmozarts\MessagingBundle\MessageGateway\QualifierBasedMessageGateway
        public: false
        arguments:
            - '@service_container'

    webmozarts_messaging.asynchronous.serialized_message_consumer:
        class: Webmozarts\MessagingBundle\Consumer\SerializedMessageConsumer
        public: false
        arguments:
            - '@serializer'
            - '@webmozarts_messaging.asynchronous.gateway'
