services:
    webmozarts_messaging.asynchronous.wrapped_messaage_with_handler_descriptors_normalizer:
        class: Webmozarts\MessagingBundle\Serializer\WrappedMessageWithHandlerDescriptorsNormalizer
        tags:
            - { name: serializer.normalizer }
