services:

    # Regular event bus middleware

    webmozarts_messaging.event_bus.publishes_async_messages_middleware:
        class: Webmozarts\MessagingBundle\MessageBus\Middleware\PublishesAsyncMessages
        public: false
        arguments:
            - '@webmozarts_messaging.asynchronous.publisher'
            - '@security.token_storage'
        tags:
            - { name: webmozarts_messaging.event_bus_middleware }

    webmozarts_messaging.event_bus.invokes_handlers_supporting_retry_middleware:
        class: Webmozarts\MessagingBundle\MessageBus\Middleware\InvokesHandlersSupportingRetry
        public: false
        arguments:
            - '@webmozarts_messaging.event_bus.handler_invoker'
            - '@webmozarts_messaging.asynchronous.publisher'
            - '@?sentry.client'
            - '@logger'
        tags:
            - { name: webmozarts_messaging.event_bus_middleware, priority: -1000 }

    # Asynchronous event bus
    
    webmozarts_messaging.asynchronous.event_bus:
        class: Webmozarts\MessagingBundle\MessageBus\EventBus
        public: true
        tags:
            - { name: webmozarts_messaging.asynchronous_message_bus, qualifier: Webmozarts\MessagingBundle\Qualifier\Event }

    webmozarts_messaging.asynchronous.event_bus.events.finishes_message_before_handling_next_middleware:
        class: SimpleBus\Message\Bus\Middleware\FinishesHandlingMessageBeforeHandlingNext
        public: false
        tags:
            - { name: webmozarts_messaging.asynchronous_event_bus_middleware, priority: 1000 }

    # No handler descriptor resolving - async events are resolved already

    webmozarts_messaging.asynchronous.event_bus.invokes_handlers_supporting_retry_middleware:
        class: Webmozarts\MessagingBundle\MessageBus\Middleware\InvokesHandlersSupportingRetry
        public: false
        arguments:
            - '@webmozarts_messaging.event_bus.handler_invoker'
            - '@webmozarts_messaging.asynchronous.publisher'
            - '@?sentry.client'
            - '@logger'
        tags:
            - { name: webmozarts_messaging.asynchronous_event_bus_middleware, priority: -1000 }
