parameters:
    webmozarts_messaging.authentication.anonymous_user_id: ~

services:
    webmozarts_messaging.authentication.user_provider:
        synthetic: true

    webmozarts_messaging.command_bus.handler_invoker.authenticates_user_middleware:
        class: Webmozarts\MessagingBundle\HandlerInvoker\Middleware\AuthenticatesUser
        public: false
        arguments:
            - '@security.token_storage'
            - '@webmozarts_messaging.authentication.user_provider'
            - '%webmozarts_messaging.authentication.anonymous_user_id%'
        tags:
            - { name: webmozarts_messaging.command_handler_invoker_middleware, priority: 100 }

    webmozarts_messaging.event_bus.handler_invoker.authenticates_user_middleware:
        class: Webmozarts\MessagingBundle\HandlerInvoker\Middleware\AuthenticatesUser
        public: false
        arguments:
            - '@security.token_storage'
            - '@webmozarts_messaging.authentication.user_provider'
            - '%webmozarts_messaging.authentication.anonymous_user_id%'
        tags:
            - { name: webmozarts_messaging.event_handler_invoker_middleware, priority: 100 }
