parameters:
    webmozarts_messaging.event_bus.logging.level: debug

services:
    webmozarts_messaging.event_bus.logging_middleware:
        class: SimpleBus\Message\Logging\LoggingMiddleware
        public: false
        arguments:
            - '@logger'
            - '%webmozarts_messaging.event_bus.logging.level%'
        tags:
            - { name: webmozarts_messaging.event_bus_middleware, priority: -999 }
            - { name: monolog.logger, channel: event_bus }
