services:
    cwd_messaging.rabbit_mq.connection:
        synthetic: true

    cwd_messaging.rabbit_mq.producer:
        class: OldSound\RabbitMqBundle\RabbitMq\Producer
        public: true
        arguments:
            - '@cwd_messaging.rabbit_mq.connection'

    cwd_messaging.rabbit_mq.consumer:
        class: Cwd\MessagingBundle\Adapter\RabbitMQ\RabbitMQMessageConsumer
        public: true
        arguments:
            - '@cwd_messaging.rabbit_mq.connection'
            - '@cwd_messaging.asynchronous.serialized_message_consumer'

    cwd_messaging.rabbit_mq.publisher:
        class: Cwd\MessagingBundle\Adapter\RabbitMQ\RabbitMQMessagePublisherSupportingAutoSetup
        public: true
        arguments:
            - '@cwd_messaging.rabbit_mq.producer'
            - '@serializer'
            - '@cwd_messaging.rabbit_mq.routing_key_resolver'
            - '@cwd_messaging.rabbit_mq.delegating_additional_properties_resolver'
            - '@cwd_messaging.channel_registry'

    cwd_messaging.asynchronous.publisher: '@cwd_messaging.rabbit_mq.publisher'

    cwd_messaging.rabbit_mq.delegating_additional_properties_resolver:
        class: SimpleBus\Asynchronous\Properties\DelegatingAdditionalPropertiesResolver
        public: false
        arguments:
            - []

    cwd_messaging.rabbit_mq.routing_key_resolver:
        class: Cwd\MessagingBundle\Routing\ExpressionLanguageBasedRoutingKeyResolver
        public: false
