services:
    webmozarts_messaging.rabbit_mq.connection:
        synthetic: true

    webmozarts_messaging.rabbit_mq.producer:
        class: OldSound\RabbitMqBundle\RabbitMq\Producer
        public: true
        arguments:
            - '@webmozarts_messaging.rabbit_mq.connection'

    webmozarts_messaging.rabbit_mq.consumer:
        class: Webmozarts\MessagingBundle\Adapter\RabbitMQ\RabbitMQMessageConsumer
        public: true
        arguments:
            - '@webmozarts_messaging.rabbit_mq.connection'
            - '@webmozarts_messaging.asynchronous.serialized_message_consumer'

    webmozarts_messaging.rabbit_mq.publisher:
        class: Webmozarts\MessagingBundle\Adapter\RabbitMQ\RabbitMQMessagePublisherSupportingAutoSetup
        public: true
        arguments:
            - '@webmozarts_messaging.rabbit_mq.producer'
            - '@serializer'
            - '@webmozarts_messaging.rabbit_mq.routing_key_resolver'
            - '@webmozarts_messaging.rabbit_mq.delegating_additional_properties_resolver'
            - '@webmozarts_messaging.channel_registry'

    webmozarts_messaging.asynchronous.publisher: '@webmozarts_messaging.rabbit_mq.publisher'

    webmozarts_messaging.rabbit_mq.delegating_additional_properties_resolver:
        class: SimpleBus\Asynchronous\Properties\DelegatingAdditionalPropertiesResolver
        public: false
        arguments:
            - []

    webmozarts_messaging.rabbit_mq.routing_key_resolver:
        class: Webmozarts\MessagingBundle\Routing\ExpressionLanguageBasedRoutingKeyResolver
        public: false
